[data_path]
windows = "D:\\ADwithAE"
linux = "/home/desmondhe/Windows_D/ADwithAE"
# linux = "/eos/user/z/zhengtin/ADwithNE"

[file]
SM = "background_for_training.h5"
neutral_boson = "Ato4l_lepFilter_13TeV_filtered.h5"
leptoquark = "leptoquark_LOWMASS_lepFilter_13TeV_filtered.h5"
neutral_Higgs = "hToTauTau_13TeV_PU20_filtered.h5"
charged_Higgs = "hChToTauNu_13TeV_PU20_filtered.h5"

[EMD]
particle_type_scale = 20
particle_one_hot = true
n_pair = 2000000
norm = false
save_emd = true
pid_method = "separate"

[Transformer]
feature_size = 3
embed_size = 16
num_heads = 8
num_layers = 4
hidden_dim = 256
output_dim = 2

[train]
num_workers = 8
prefetch_factor = 32
batch_size = 256

[lambda_estimate]
T = 0.5
n_bins = 20

[sig_color]
leptoquark = "#FFBE7A"
neutral_boson = "#8ECFC9"
neutral_Higgs = "#FA7F6F"
charged_Higgs = "#D4ACF4"
SM = "#B8C7D1"

[event_color]
Electron = "#4D9DE0"
Muon = "#E15554"
Electron_Muon = "#3BB273"
Electron_Jets = "#7768AE"
Muon_Jets = "#EB8A44"
Electron_Muon_Jets = "#FFC15E"

[hypothesis_test]
n = 500000
n_null = 2000

[threshold]
lrt = 0.014815863868755264
mce = 0.49852925000000003
auc = 0.50212982325
